@startuml
'https://plantuml.com/class-diagram

hide circle
skinparam linetype ortho

entity "onetomany_bidirect_posts" as Post {
    id: bigint not null
    --
    title: varchar(255)
}

entity "onetomany_bidirect_comments" as Comment {
    id: bigint not null
    --
    parentpost_id: bigint
    --
    review: varchar(255)
}

Post ||--o{ Comment
@enduml